// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhbeh29C80ErSF7NDaHcTPOUxmfCDnKk',
    appId: '1:961968261867:web:c19dcb8351d14bf8ee0cae',
    messagingSenderId: '961968261867',
    projectId: 'authdevhack',
    authDomain: 'authdevhack.firebaseapp.com',
    storageBucket: 'authdevhack.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFiJjDQDvIkIBN0_C-y-HjrAkE0UM4EE',
    appId: '1:961968261867:android:0c1eb330b35508a1ee0cae',
    messagingSenderId: '961968261867',
    projectId: 'authdevhack',
    storageBucket: 'authdevhack.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDasrwv94nlWGam8RKobnIK3SoshZi0jd8',
    appId: '1:961968261867:ios:05277b4bcc3bc3fcee0cae',
    messagingSenderId: '961968261867',
    projectId: 'authdevhack',
    storageBucket: 'authdevhack.appspot.com',
    iosBundleId: 'com.example.devhacktesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDasrwv94nlWGam8RKobnIK3SoshZi0jd8',
    appId: '1:961968261867:ios:90a169efc3f1fedbee0cae',
    messagingSenderId: '961968261867',
    projectId: 'authdevhack',
    storageBucket: 'authdevhack.appspot.com',
    iosBundleId: 'com.example.devhacktesting.RunnerTests',
  );
}
